<?php

/*
|--------------------------------------------------------------------------
| Trend focus & hack signals
|--------------------------------------------------------------------------
| Product decision: the tool prioritizes practical, hands-on content about
| Laravel, PHP/TypeScript basics, React, Next.js and databases (MySQL etc.)
| in the short "hack / tip / trick" style. This is a SOFT boost — nothing is
| hidden, focus-matching trends simply rank higher via the topic_focus
| scoring dimension. Hack-style phrasing further boosts practical usefulness.
|
| Slugs must match technologies.slug (generated by TechnologySeeder via
| Str::slug) and categories.slug.
*/

return [

    'focus' => [
        'technology_slugs' => [
            'laravel',
            'php',
            'react',
            'next-js',
            'typescript',
            'mysql',
            'mariadb',
            'postgresql',
            'sqlite',
        ],

        // Matching the category alone earns a smaller boost than a
        // registry technology match (100 vs 55).
        'category_slugs' => [
            'databases',
        ],
    ],

    /*
    | Word-boundary matched against title + summary (case-insensitive).
    | Kept separate from the generic usefulness signals so false positives
    | like "multiple" containing "tip" can't leak in.
    */
    'hack_keywords' => [
        'tip', 'tips',
        'trick', 'tricks',
        'hack', 'hacks',
        'shortcut', 'shortcuts',
        'one-liner', 'one liner',
        'cheat sheet',
        'gotcha', 'gotchas',
        'snippet', 'snippets',
        'n+1',
        'explain',
        'query plan',
        'index', 'indexes', 'indexing',
        'debug', 'debugging',
        'refactor', 'refactoring',
        'migration', 'migrations',
        'performance',
        'faster',
        'productivity',
    ],

    // A trend is badged "hack style" once this many distinct keywords hit.
    'hack_style_min_hits' => 2,

    // usefulness bonus per distinct hack keyword, capped to keep the
    // dimension honest (55 base -> max 100).
    'hack_bonus_per_hit' => 9,
    'hack_bonus_max_hits' => 3,
];
